config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'purchases/index'

  get 'purchases/home'

  devise_for :users
  get 'units/index'

  get 'units/home'

  resources :fiscal_years

  get 'fiscal_years/home'


  resources :company_profiles do
    collection do
      get :manage_company_profiles
    end
  end
  resources :logs
  resources :purchases
  resources :customers
  resources :suppliers
  resources :units
  resources :item_groups
  resources :stocks
  resources :items
  resources :items do
    collection do
      get :manage_items
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1}
  validates :address, presence: true, length: {minimum: 1}
  validates :vdc_mun, presence: true, length: {minimum: 2}
  validates :ward_no, presence: true, numericality: {only_integer: 2}
  validates :phone_no, presence: true, numericality: {only_integer: 2}
  validates :vat_pan_no, presence: true, length: {minimum: 1}

  validates :district, presence: true, length: {minimum: 1}
  validates :zone, presence: true, length: {minimum: 1}

  mount_uploader :logo_url,LogoUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :purchases
  has_one :stocks
  accepts_nested_attributes_for :stocks
  validates :item_group_id, presence: true
  validates :name, presence: true, length: {minimum: 1}
  validates :unit_id, presence: true, numericality: {only_integer: 2}
  validates :item_code, presence: true, length: {minimum: 2}
  validates :quantity, presence: true, numericality: {only_integer: 2}
  validates :description, presence: true, length: {minimum: 2}
  validates :item_group_id, presence: true, numericality: {only_integer: 2}
  validates :expiry_date, presence: true, length: {minimum: 1}
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items
  validates :name, presence: true
  #validates :parent_id, presence: true
  validates :description, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
 belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_item
  has_many :item
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item
  accepts_nested_attributes_for :purchase, allow_destroy: true
end

app/models/stock.rb
class Stock < ApplicationRecord
belongs_to :items
  validates :quantity, presence: true
  validates :unit_price, presence: true
  validates :est_sell_price, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :logs
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @redirect_toadmin_index_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= link_to item_groups_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("group.png") %>
              <h3>ItemGroups</h3>
            </div>
      <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <%= link_to customers_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("Customer.png") %>
              <h3>Customer</h3>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to suppliers_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("suppliers.png") %>
              <h3>Suppliers</h3>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= link_to items_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("items.png") %>
              <h3>Items</h3>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to purchases_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("purchases.png") %>
              <h3>Purchases</h3>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to stocks_path do %>
          <div class="well">
            <div align="center">
              <%= image_tag("stocks.png") %>
              <h3>Stock</h3>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<% else %>

<% end %>