config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'purchases/index'

  get 'purchases/home'

  devise_for :users
  get 'units/index'

  get 'units/home'

  resources :fiscal_years

  get 'fiscal_years/home'


  resources :company_profiles do
    collection do
      get :manage_company_profiles
    end
  end
  resources :logs
  resources :purchases
  resources :customers
  resources :suppliers
  resources :units
  resources :item_groups
  resources :stocks
  resources :items
  resources :items do
    collection do
      get :manage_items
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1}
  validates :address, presence: true, length: {minimum: 1}
  validates :vdc_mun, presence: true, length: {minimum: 2}
  validates :ward_no, presence: true, numericality: {only_integer: 2}
  validates :phone_no, presence: true, numericality: {only_integer: 2}
  validates :vat_pan_no, presence: true, length: {minimum: 1}

  validates :district, presence: true, length: {minimum: 1}
  validates :zone, presence: true, length: {minimum: 1}

  mount_uploader :logo_url,LogoUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :purchases
  has_one :stocks
  accepts_nested_attributes_for :stocks
  validates :item_group_id, presence: true
  validates :name, presence: true, length: {minimum: 1}
  validates :unit_id, presence: true, numericality: {only_integer: 2}
  validates :item_code, presence: true, length: {minimum: 2}
  validates :quantity, presence: true, numericality: {only_integer: 2}
  validates :description, presence: true, length: {minimum: 2}
  validates :item_group_id, presence: true, numericality: {only_integer: 2}
  validates :expiry_date, presence: true, length: {minimum: 1}
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items
  validates :name, presence: true
  #validates :parent_id, presence: true
  validates :description, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
 belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_item
  has_many :item
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item
  accepts_nested_attributes_for :purchase, allow_destroy: true
end

app/models/stock.rb
class Stock < ApplicationRecord
belongs_to :items
  validates :quantity, presence: true
  validates :unit_price, presence: true
  validates :est_sell_price, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :logs
end

app/controllers/item_groups_controller.rb
class ItemGroupsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "ItemGroups", :item_groups_path
  def new
    add_breadcrumb "New", :new_item_group_path
    @item_groups = ItemGroup.new
  end

  def create
    @item_groups = ItemGroup.new(item_groups_param)
    if @item_groups.save
      @log = Log.create(description: "Added new itemgroup"+" "+@item_groups.name, user: current_user)
      redirect_to @item_groups
    else
      render 'new'
    end
  end

  def show
    @item_groups = ItemGroup.find(params[:id])
  end

  def index
    @item_groups = ItemGroup.all
  end


  def edit
    @item_groups = ItemGroup.find(params[:id])
    @log = Log.create(description: "Edited new itemgroup"+" "+@item_groups.name, user: current_user)
  end

  def update
    @item_groups = ItemGroup.find(params[:id])
    @item_groups.update(item_groups_param)
    redirect_to @item_groups
  end

  def destroy
    @item_groups = ItemGroup.destroy(params[:id])
    @log = Log.create(description: "Deleted new itemgroup"+" "+@item_groups.name, user: current_user)
    redirect_to @item_groups
  end
  def manage_item_groups
    @title="manage item_groups"
    @item_groups = ItemGroup.all
    add_breadcrumb "manage item_groups", :item_groups_path
  end

  private
  def item_groups_param
    params.require(:item_group).permit(:name, :parent, :description)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_groups_helper.rb
module ItemGroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/item_groups/edit.html.erb
<%= form_for @item_groups, :html => {:class => "new-horizontal"} do |f| %>
<div class="well">
  <div class="form-group">
    <label class="control-label col-md-2" for="name"> Name </label>
    <div class="col-md-7">
      <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Enter Name" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2" for="parent_id">Parent-Id</label>
    <div class="col-md-7">
      <%=f.collection_select :parent_id, Item.order(:name), :id, :name, {prompt: "Select Category"}, {class: "new-control"}%>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2" for="description">Description</label>
    <div class="col-md-7">
      <%= f.text_area :description, :class => "new-control", :id => "description", :placeholder => "Description" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit(type: 'submit', class: "btn btn-success") %>
    </div>
  </div>
  </form>
</div>
<% end %>

app/views/item_groups/home.html.erb
<h1>ItemGroups#home</h1>
<p>Find me in app/views/item_groups/home.html.erb</p>

app/views/item_groups/index.html.erb
<div class="row" xmlns:font-size="http://www.w3.org/1999/xhtml">
  <table class="table table-striped table-bordered">
    <div class="action text-right">
      <a href="<%= new_item_group_path %>" class="btn btn-primary"><span><i class="fa fa-plus-square"></i></span>New</a>

    </div>
    <tr>
      <th>Name</th>
      <th>Parent-Id</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    <% @item_groups.each do |item_groups| %>
        <tr>
          <td><%= item_groups.name %></td>
          <td><%= item_groups.parent_id %></td>
          <td><%= item_groups.description %></td>
          <td><%= link_to "", edit_item_group_path(item_groups), :class => "fa fa-pencil", :title => "Edit" %>
          <%= link_to "",item_group_path(item_groups),:class => "fa fa-trash", :title => "Delete",
                          method: :delete,
                          data: {confirm: "Are you sure"} %></td>

        </tr>

    <% end %>
  </table>
</div>

app/views/item_groups/new.html.erb
<%= form_for @item_groups, :html => {:class => "new-horizontal"} do |f| %>
    <div class="alert-danger">
      <% if @item_groups.errors.any? %>
          <h2>
            <%= pluralize(@item_groups.errors.count, "error") %>
            occured
          </h2>
          <ul>
            <%= @item_groups.errors.full_messages.each do |e| %>
                <li> <%= e %>
                </li>
            <% end %>
          </ul>

      <% end %>
    </div>
    <div class="well">
      <div class="form-group">
        <label class="control-label col-md-2" for="name"> Name </label>
        <div class="col-md-7">
          <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Enter Name" %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2" for="parent_id">Parent-Id</label>
        <div class="col-md-7">
          <%=f.collection_select :parent_id, ItemGroup.order(:name), :id, :name, {prompt: "Select Category"}, {class: "new-control"}%>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2" for="description">Description</label>
        <div class="col-md-7">
          <%= f.text_area :description, :class => "new-control", :id => "description", :placeholder => "Description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(type: 'submit', class: "btn btn-success") %>
        </div>
      </div>
      </form>
    </div>
<% end %>

app/views/item_groups/show.html.erb
<div class="container">

  <p> <b> Name: </b> <%= @item_groups.name %> </p>

  <p> <b> Parent-Id: </b> <%= @item_groups.parent_id %> </p>

  <p> <b> Description: </b> <%= @item_groups.description %> </p>

  </p>
</div>