config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'purchases/index'

  get 'purchases/home'

  devise_for :users
  get 'units/index'

  get 'units/home'

  resources :fiscal_years

  get 'fiscal_years/home'


  resources :company_profiles do
    collection do
      get :manage_company_profiles
    end
  end
  resources :logs
  resources :purchases
  resources :customers
  resources :suppliers
  resources :units
  resources :item_groups
  resources :stocks
  resources :items
  resources :items do
    collection do
      get :manage_items
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1}
  validates :address, presence: true, length: {minimum: 1}
  validates :vdc_mun, presence: true, length: {minimum: 2}
  validates :ward_no, presence: true, numericality: {only_integer: 2}
  validates :phone_no, presence: true, numericality: {only_integer: 2}
  validates :vat_pan_no, presence: true, length: {minimum: 1}

  validates :district, presence: true, length: {minimum: 1}
  validates :zone, presence: true, length: {minimum: 1}

  mount_uploader :logo_url,LogoUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :purchases
  has_one :stocks
  accepts_nested_attributes_for :stocks
  validates :item_group_id, presence: true
  validates :name, presence: true, length: {minimum: 1}
  validates :unit_id, presence: true, numericality: {only_integer: 2}
  validates :item_code, presence: true, length: {minimum: 2}
  validates :quantity, presence: true, numericality: {only_integer: 2}
  validates :description, presence: true, length: {minimum: 2}
  validates :item_group_id, presence: true, numericality: {only_integer: 2}
  validates :expiry_date, presence: true, length: {minimum: 1}
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items
  validates :name, presence: true
  #validates :parent_id, presence: true
  validates :description, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
 belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_item
  has_many :item
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item
  accepts_nested_attributes_for :purchase, allow_destroy: true
end

app/models/stock.rb
class Stock < ApplicationRecord
belongs_to :items
  validates :quantity, presence: true
  validates :unit_price, presence: true
  validates :est_sell_price, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :logs
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Units", :units_path
  def new
    add_breadcrumb "New", :new_unit_path
    @units = Unit.new
  end

  def create
    @units = Unit.new(units_param)
    if @units.save
      @log = Log.create(description: "Added new unit"+" "+@units.name, user: current_user)
      redirect_to @units
    else
      render 'new'
    end
  end

  def show
    @units = Unit.find(params[:id])
  end

  def index
    @units = Unit.all
  end


  def edit
    @units = Unit.find(params[:id])
    @log = Log.create(description: "Edited new unit"+" "+@units.name, user: current_user)
  end

  def update
    @units = Unit.find(params[:id])
    @units.update(units_param)
    redirect_to @units
  end

  def destroy
    @units = Unit.destroy(params[:id])
    @log = Log.create(description: "Deleted new unit"+" "+@units.name, user: current_user)
    redirect_to @units
  end
  def manage_units
    @title="manage units"
    @Units = Unit.all
    add_breadcrumb "manage units", :units_path
  end

  private
  def units_param
    params.require(:unit).permit(:name, :print_name)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/edit.html.erb
<%= form_for @units, :html => {:class => "new-horizontal"} do |f| %>
<div class="well">
  <div class="form-group">
    <label class="control-label col-md-2" for="name"> Name </label>
    <div class="col-md-7">
      <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Name" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2" for="print_name">Print-name</label>
    <div class="col-md-7">
      <%= f.text_field :print_name, :class => "new-control", :id => "print_name", :placeholder => "Print-name" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit(type: 'submit', class: "btn btn-success") %>
    </div>
    </form>
  </div>
</div>
<% end %>

app/views/units/home.html.erb
<h1>Units#home</h1>
<p>Find me in app/views/units/home.html.erb</p>

app/views/units/index.html.erb
<div class="row">
  <table class="table table-striped table-bordered">
    <div class="action text-right">
      <a href="<%= new_unit_path %>" class="btn btn-primary"><span><i class="fa fa-plus-square"></i></span>New</a>
    </div>
    <tr>
      <th>Name</th>
      <th>Print-name</th>
      <th>Actions</th>
    </tr>
    <% @units.each do |unit| %>
        <tr>
          <td><%= unit.name %></td>
          <td><%= unit.print_name %></td>
          <td> <%= link_to "", edit_unit_path(unit), :class => "fa fa-pencil", :title => "Edit" %>
            <%= link_to "", unit_path(unit), :class => "fa fa-trash", :title => "delete",
                        method: :delete,
                        data: {confirm: "Are you sure"} %></td>
        </tr>

    <% end %>
  </table>
</div>

app/views/units/new.html.erb
<%= form_for @units, :html => {:class => "new-horizontal"} do |f| %>
    <div class="alert-danger">
      <% if @units.errors.any? %>
          <h2>
            <%= pluralize(@units.errors.count,"error")  %>
            occured
          </h2>
          <ul>
            <%= @units.errors.full_messages.each do |e| %>
                <li> <%= e %>
                </li>
            <% end %>
          </ul>
          </div>
      <% end %>
      <div class="well">
        <div class="form-group">
          <label class="control-label col-md-2" for="name"> Name </label>
          <div class="col-md-7">
            <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Name" %>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-md-2" for="print_name">Print-name</label>
          <div class="col-md-7">
            <%= f.text_field :print_name, :class => "new-control", :id => "print_name", :placeholder => "Print-name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit(type: 'submit', class: "btn btn-success") %>
        </div>
        </form>
      </div>
      </div>


<% end %>

app/views/units/show.html.erb
<div class="container">

  <p> <b> Name: </b> <%= @units.name %> </p>

  <p> <b> Print-name: </b> <%= @units.print_name %> </p>


</div>