config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'purchases/index'

  get 'purchases/home'

  devise_for :users
  get 'units/index'

  get 'units/home'

  resources :fiscal_years

  get 'fiscal_years/home'


  resources :company_profiles do
    collection do
      get :manage_company_profiles
    end
  end
  resources :logs
  resources :purchases
  resources :customers
  resources :suppliers
  resources :units
  resources :item_groups
  resources :stocks
  resources :items
  resources :items do
    collection do
      get :manage_items
    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1}
  validates :address, presence: true, length: {minimum: 1}
  validates :vdc_mun, presence: true, length: {minimum: 2}
  validates :ward_no, presence: true, numericality: {only_integer: 2}
  validates :phone_no, presence: true, numericality: {only_integer: 2}
  validates :vat_pan_no, presence: true, length: {minimum: 1}

  validates :district, presence: true, length: {minimum: 1}
  validates :zone, presence: true, length: {minimum: 1}

  mount_uploader :logo_url,LogoUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :purchases
  has_one :stocks
  accepts_nested_attributes_for :stocks
  validates :item_group_id, presence: true
  validates :name, presence: true, length: {minimum: 1}
  validates :unit_id, presence: true, numericality: {only_integer: 2}
  validates :item_code, presence: true, length: {minimum: 2}
  validates :quantity, presence: true, numericality: {only_integer: 2}
  validates :description, presence: true, length: {minimum: 2}
  validates :item_group_id, presence: true, numericality: {only_integer: 2}
  validates :expiry_date, presence: true, length: {minimum: 1}
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items
  validates :name, presence: true
  #validates :parent_id, presence: true
  validates :description, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
 belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_item
  has_many :item
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item
  accepts_nested_attributes_for :purchase, allow_destroy: true
end

app/models/stock.rb
class Stock < ApplicationRecord
belongs_to :items
  validates :quantity, presence: true
  validates :unit_price, presence: true
  validates :est_sell_price, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_no, presence: true
  validates :email,presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :logs
end

app/controllers/fiscal_years_controller.rb
class FiscalYearsController < ApplicationController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Fiscal_years", :fiscal_years_path
  def new
    add_breadcrumb "New", :new_fiscal_year_path
    @fiscal_years = FiscalYear.new
  end

  def create
    @fiscal_years = FiscalYear.new(fiscal_years_param)
    if @fiscal_years.save
      @log = Log.create(description: "Added new fiscalyear"+" "+@fiscal_years.name, user: current_user)
      redirect_to @fiscal_years
    else
      render 'new'
    end
  end

  def show
    @fiscal_years = FiscalYear.find(params[:id])
  end

  def index

    @fiscal_years = FiscalYear.all
  end


  def edit
    @fiscal_years = FiscalYear.find(params[:id])
    @log = Log.create(description: "Edited new fiscalyear"+" "+@fiscal_years.name, user: current_user)
  end

  def update
    @fiscal_years = FiscalYear.find(params[:id])
    @fiscal_years.update(fiscal_years_param)
    redirect_to @fiscal_years
  end

  def destroy
    @fiscal_years = FiscalYear.destroy(params[:id])
    @log = Log.create(description: "Deleted new fiscalyear"+" "+@fiscal_years.name, user: current_user)
    redirect_to @fiscal_years
  end
  def manage_fiscal_years
    @title="manage fiscal_years"
    @fiscal_years = FiscalYear.all
    add_breadcrumb "manage items", :fiscal_years_path
  end

  private
  def fiscal_years_param
    params.require(:fiscal_year).permit(:name, :start_date, :end_date)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fiscal_years_helper.rb
module FiscalYearsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/fiscal_years/edit.html.erb
<div class="container">
  <%= form_for @fiscal_years, :html => {:class => "new-horizontal"} do |f| %>
      <div class="alert-danger">
        <% if @fiscal_years.errors.any? %>
            <h2>
              <%= pluralize(@fiscal_years.errors.count,"error")  %>
              occured
            </h2>
            <ul>
              <%= @fiscal_years.errors.full_messages.each do |e| %>
                  <li> <%= e %>
                  </li>
              <% end %>
            </ul>
            </div>
        <% end %>
        <div class="well">
          <div class="form-group">
            <label class="control-label col-md-2" for="name"> Name </label>
            <div class="col-md-7">
              <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Name" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-2" for="start_date">Start-date</label>
            <div class="col-md-7">
              <%= f.text_field :start_date, :class => "new-control", :id => "datepicker", :placeholder => "YY/MM/DD" %>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-md-2" for="end_date">End-date</label>
            <div class="col-md-7">
              <%= f.text_field :end_date, :class => "new-control", :id => "date", :placeholder => "YY/MM/DD" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit(type: 'submit', class: "btn btn-success") %>
            </div>
          </div>
        </div>
        </div>
        <script src="datepicker.css"></script>
        <script src="bootstrap-datepicker.js"></script>

        <script>
          $('#datepicker').datepicker();
        </script>
        <script>
          $('#date').datepicker();
        </script>
  <% end %>


  </div>

app/views/fiscal_years/home.html.erb
<h1>FiscalYears#home</h1>
<p>Find me in app/views/fiscal_years/home.html.erb</p>

app/views/fiscal_years/index.html.erb
<div class="row">
  <table class="table table-striped table-bordered">
    <div class="action text-right">
      <a href="<%= new_fiscal_year_path %>" class="btn btn-primary"><span><i class="fa fa-plus-square"></i></span>New</a>

    </div>
    <tr>
      <th>Name</th>
      <th>Start-date</th>
      <th>End-date</th>
      <th>Actions</th>
    </tr>
    <% @fiscal_years.each do |fiscal_years| %>
        <tr>
          <td><%= fiscal_years.name %></td>
          <td><%= fiscal_years.start_date %></td>
          <td><%= fiscal_years.end_date %></td>
          <td><%= link_to "", edit_fiscal_year_path(fiscal_years), :class => "fa fa-pencil", :title => "Edit" %>
          <%= link_to "", fiscal_year_path(fiscal_years), :class => "fa fa-trash", :title => "delete",
                          method: :delete,
                          data: {confirm: "Are you sure"} %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/fiscal_years/new.html.erb
<%= form_for @fiscal_years, :html => {:class => "new-horizontal"} do |f| %>
    <div class="alert-danger">
    <% if @fiscal_years.errors.any? %>
        <h2>
          <%= pluralize(@fiscal_years.errors.count,"error")  %>
          occured
        </h2>
        <ul>
          <%= @fiscal_years.errors.full_messages.each do |e| %>
              <li> <%= e %>
              </li>
          <% end %>
        </ul>
          </div>
    <% end %>
    <div class="well">
      <div class="form-group">
        <label class="control-label col-md-2" for="name"> Name </label>
        <div class="col-md-7">
          <%= f.text_field :name, :class => "new-control", :id => "name", :placeholder => "Name" %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2" for="start_date">Start-date</label>
        <div class="col-md-7">
          <%= f.text_field :start_date, :class => "new-control", :id => "datepicker", :placeholder => "YY/MM/DD" %>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-md-2" for="end_date">End-date</label>
        <div class="col-md-7">
          <div class="input-group date">
          <%= f.text_field :end_date, :class => "new-control datepicker", :placeholder => "YY/MM/DD" %>
          <label for="fiscal_year_expiry_date" class="input-group-addon add-on"><i class="fa fa-calendar"></i></label>
        </div>
      </div>
        </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(type: 'submit', class: "btn btn-success") %>
        </div>
      </div>
      </form>
    </div>
    </div>
    <script src="datepicker.css"></script>
    <script src="bootstrap-datepicker.js"></script>

    <script>
      $('#datepicker').datepicker({
        'format':'yyyy-mm-dd'
      });
    </script>
    <script>
      $('.datepicker').datepicker({
        'format':'yyyy-mm-dd'
      });
    </script>
<% end %>

app/views/fiscal_years/show.html.erb
<div class="container">

  <p> <b> Name: </b> <%= @fiscal_years.name %> </p>

  <p> <b> Start-date: </b> <%= @fiscal_years.start_date %> </p>

  <p> <b> End-date: </b> <%= @fiscal_years.end_date %> </p>

</div>